name: Go Check
on: [push, pull_request]
jobs:
  buildable:
    name: Buildable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - run: go run ./cmd/cdk/cdk.go
