name: Go Check
on:
  pull_request:
    branches:
    - feature/*
  push:
    branches:
    - feature/*
jobs:
  buildable:
    name: Buildable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: "cedrickring/golang-action@1.3.0"
      with:
        args: go build ./cmd/cdk/cdk.go
